dbt_brasileirao:
  outputs:
    dev:
      dataset: brasileirao
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: gcp_storage_credentials.json
      location: US
      method: service-account
      priority: interactive
      project: gcp-brasileirao-gcp
      threads: 1
      type: bigquery
  target: dev
