dbt_brasileirao:
  outputs:
    dev:
      type: bigquery
      project: gcp-brasileirao
      schema: curated
      keyfile: ../../gcp_storage_credentials.json
      location: US
      method: service-account
      job_execution_timeout_seconds: 300
      job_retries: 1
      priority: interactive
      threads: 1
  target: dev
